apps/products/urls.py
from django.urls import path

from apps.products.views import ProductsListView, basket_add, basket_remove

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='product_by_category'),
    path('basket/<int:product_id>', basket_add, name='basket_add'),
    path('profile/<int:basket_id>', basket_remove, name='basket_remove'),
]

gog/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from apps.orders.views import stripe_webhook_view
from apps.products.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('apps.products.urls', namespace='products')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('apps.api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
import stripe
from django.db import models
from django.db.models import Sum

from apps.users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    @classmethod
    def with_product_count(cls):
        return cls.objects.annotate(total_quantity=Sum('products__quantity'))


class Product(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="products_images")
    stripe_product_price_id = models.CharField(max_length=128, null=True, blank=True)
    category = models.ForeignKey(ProductCategory, related_name='products', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    @classmethod
    def available(cls, category_id=None):
        queryset = cls.objects.filter(quantity__gte=1)
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def save(self, *args, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super().save(*args, force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price * 100), currency='rub'
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'{self.user}: {self.product} - {self.quantity}'

    def sum(self):
        return self.quantity * self.product.price

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item

    @classmethod
    def create_or_update(cls, product_id, user):
        baskets = Basket.objects.filter(user=user, product_id=product_id)

        if not baskets.exists():
            obj = Basket.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
            is_created = False
            return basket, is_created

apps/products/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import ListView, TemplateView

from .models import Basket, Product, ProductCategory


class IndexTemplateView(TemplateView):
    extra_context = {'title': 'Grace of the Gods'}
    template_name = 'index.html'


@method_decorator(cache_page(30), name='dispatch')
@method_decorator(vary_on_cookie, name='dispatch')
class ProductsListView(ListView):
    extra_context = {'title': 'Каталог'}
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3

    def get_queryset(self):
        category_id = self.kwargs.get('category_id')
        queryset = Product.available()
        if category_id is not None:
            queryset = queryset.filter(category_id=category_id)
        return queryset.order_by('id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        visible_categories = ProductCategory.with_product_count().filter(total_quantity__gte=1)
        context['visible_categories'] = visible_categories

        return context


@login_required
def basket_add(request, product_id):
    Basket.create_or_update(product_id, request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

templates/products/products.html
{% extends 'base.html' %}
{% load static cache humanize %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/products/products.css' %}">
{% endblock %}
{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block content %}
    <nav class="category-nav">
        <a href="{% url 'products:index' %}"
           class="category-button">Все категории</a>
        {% for category in visible_categories %}
            <a href="{% url 'products:product_by_category' category.id %}"
               class="category-button">{{ category.name }}</a>
        {% endfor %}
    </nav>
    <body class="white-background">
    <section class="product-list">
        {% for product in object_list %}
            <div class="product-card">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                <h2>{{ product.name }}</h2>
                <p>{{ product.description }}</p>
                <p class="price">Цена: {{ product.price | intcomma }} Р.</p>
                <a href="{% url 'products:basket_add' product.id %}"
                   class="buy-button">Купить</a>
            </div>
        {% endfor %}
    </section>
    <div class="pagination">
            <span class="step-links">
                {% for paginated_products_page in page_obj.paginator.page_range %}
                    {% if paginated_products_page == page_obj.number %}
                        <span class="current">
                            {{ page_obj.number }}
                        </span>
                    {% else %}
                        <a href="?page={{ paginated_products_page }}">{{ paginated_products_page }}</a>
                    {% endif %}
                {% endfor %}
            </span>
    </div>
    </body>
{% endblock %}