apps/orders/urls.py
from django.urls import path

from apps.orders.views import (CanceledTemplateView, OrderCreateView,
                               OrderDetailView, OrderListView,
                               SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from apps.users.views import (CustomPasswordResetCompleteView,
                              CustomPasswordResetConfirmView,
                              CustomPasswordResetDoneView,
                              CustomPasswordResetView, EmailVerificationView,
                              UserLoginView, UserProfileView,
                              UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='registration'),
    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

gog/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from apps.orders.views import stripe_webhook_view
from apps.products.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('apps.products.urls', namespace='products')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('apps.api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %} {% endblock %}
    {% block title %}
        <title>Grace of the Gods</title>
    {% endblock %}
</head>
<body>
<header>
    <div class="logo"><a href="{% url 'index' %}">Grace of the Gods</a></div>
    <nav>
        <ul class="right">
            <li><a href="{% url 'products:index' %}">Каталог</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:profile' user.pk %}">Профиль</a></li>
                <li><a href="{% url 'orders:orders_list' %}">Заказы</a></li>
                {% if user.is_superuser or user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Админ панель</a></li>
                {% endif %}
                <li>
                    <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="exit-button">Выйти</button>
                    </form>
                </li>
            {% else %}
                <li class="margin-right: 20px;"><a href="{% url 'users:login' %}">Войти</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
<div class="separator"></div>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
     <title>{{ title }}</title>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block content %}
    <body>
        <div class="content">
            <p class="black-text">Погрузитесь в мир изысканной одежды, разработанной с любовью и вниманием к деталям.
                Наши коллекции вдохновлены богами, чтобы даровать вам чувство стиля и уверенности.
                Проводите время, наслаждаясь качественными материалами и уникальным дизайном, которые помогут вам
                выделиться
                из толпы!</p>
            <a href="{% url 'products:index' %}" class="shop-button">Начать покупки</a>
        </div>
    </body>
{% endblock %}