apps/orders/urls.py
from django.urls import path

from apps.orders.views import (CanceledTemplateView, OrderCreateView,
                               OrderDetailView, OrderListView,
                               SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

gog/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from apps.orders.views import stripe_webhook_view
from apps.products.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('apps.products.urls', namespace='products')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('apps.api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orders/models.py
from django.db import models

from apps.products.models import Basket
from apps.users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    address = models.CharField(max_length=64)
    basket_history = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.PositiveSmallIntegerField(default=0, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

apps/orders/forms.py
from django import forms

from apps.orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.TextInput())
    address = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

apps/orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from apps.orders.forms import OrderForm
from apps.orders.models import Order
from apps.products.models import Basket

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TemplateView):
    extra_context = {'title': 'Спасибо за заказ!'}
    template_name = 'orders/success.html'


class CanceledTemplateView(TemplateView):
    extra_context = {'title': 'Оплата отменена!'}
    template_name = 'orders/canceled.html'


class OrderListView(ListView):
    template_name = 'orders/orders.html'
    extra_context = {'title': 'Заказы'}
    queryset = Order.objects.all()
    ordering = ('-id',)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Заказ #{self.object.id}'
        return context


class OrderCreateView(CreateView):
    extra_context = {'title': 'Оформление заказа'}
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)

        if self.object:
            baskets = Basket.objects.filter(user=self.request.user)
            checkout_session = stripe.checkout.Session.create(
                line_items=baskets.stripe_products(),
                metadata={'order_id': self.object.id},
                mode='payment',
                success_url=settings.DOMAIN_NAME + reverse('orders:order_success'),
                cancel_url=settings.DOMAIN_NAME + reverse('orders:order_canceled'),
            )
            return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

        return response


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        return HttpResponse(status=400)

    if (
            event['type'] == 'checkout.session.completed' or event['type'] == 'checkout.session.async_payment_succeeded'
    ):
        fulfill_checkout(event['data']['object']['id'])

    return HttpResponse(status=200)


def fulfill_checkout(session_id):
    checkout_session = stripe.checkout.Session.retrieve(
        session_id,
        expand=['line_items'],
    )
    order_id = int(checkout_session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()
    # if checkout_session.payment_status != 'unpaid':

templates/orders/canceled.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/orders/success.css' %}" rel="stylesheet"/>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <body>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Оплата отменена</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Ваш заказ был отменен.
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
    </div>
</div>
</body>
</html>

templates/orders/order-create.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block css %}
    <link href="{% static 'css/orders/order-create.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <body>
    <section>
        {% if form.errors %}
            <div class="notification" id="notification">
                <span class="close-btn" onclick="closeNotification()">&times;</span>
                <ul>
                    {% for field, errors in form.errors.items %}
                        <li>{{ errors|join:", " }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Корзина</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }} товара</span>
                    </h4>
                    <ul class="list-group mb-3">
                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name }}</h6>
                                    <small class="text-muted">{{ basket.quantity }}</small>
                                </div>
                                <span class="text-muted">{{ basket.sum | intcomma }}</span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ baskets.total_sum | intcomma }}</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:order_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.address.id_for_label }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>

                </div>
            </div>
        </div>
    </section>

    <script>
        function closeNotification() {
            document.getElementById('notification').style.display = 'none';
        }
    </script>
    </body>
{% endblock %}

templates/orders/order.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block css %}
    <link href="{% static 'css/orders/order.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <body>
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказ #{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Кол-во</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Сумма</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for purchased_item in object.basket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ purchased_item.product_name }}
                                </th>
                                <td>{{ purchased_item.quantity }}</td>
                                <td>{{ purchased_item.price|intcomma }}</td>
                                <td>{{ purchased_item.sum|intcomma }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum|intcomma }} руб.</p>
                </div>
            </div>
        </div>
    </section>
    </body>
{% endblock %}

templates/orders/orders.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}
{% block css %}
    <link href="{% static 'css/orders/orders.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <body>
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                        <tr>
                            <td>{{ order.get_status_display }}</td>
                            <td>{{ order.created_at|naturaltime }}</td>
                            <td>{{ order.basket_history.total_sum|intcomma }}</td>
                            <td>
                                <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    </body>
{% endblock %}

templates/orders/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/orders/success.css' %}" rel="stylesheet"/>
</head>
<body class="bg-white">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header">
                            <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>
                                Ваш заказ успешно сформирован.
                            </h4>
                            <a href="{% url 'products:index' %}" class="continue-button">Продолжить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>