apps/orders/urls.py
from django.urls import path

from apps.orders.views import (CanceledTemplateView, OrderCreateView,
                               OrderDetailView, OrderListView,
                               SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
]

apps/products/urls.py
from django.urls import path

from apps.products.views import ProductsListView, basket_add, basket_remove

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsListView.as_view(), name='product_by_category'),
    path('basket/<int:product_id>', basket_add, name='basket_add'),
    path('profile/<int:basket_id>', basket_remove, name='basket_remove'),
]

apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from apps.users.views import (CustomPasswordResetCompleteView,
                              CustomPasswordResetConfirmView,
                              CustomPasswordResetDoneView,
                              CustomPasswordResetView, EmailVerificationView,
                              UserLoginView, UserProfileView,
                              UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='registration'),
    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

gog/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from apps.orders.views import stripe_webhook_view
from apps.products.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('apps.products.urls', namespace='products')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('apps.api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    is_verified_email = models.BooleanField(default=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['email'], name='unique_email_constraint')
        ]


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи для {} перейдите по ссылке: {}'.format(
            self.user.username,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return now() >= self.expires_at

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from apps.users.models import User
from apps.users.tasks import send_email_verification


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput())
    email = forms.EmailField(label='Электронная почта', widget=forms.TextInput())
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput())
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ['first_name', 'image']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password']

apps/users/views.py
from django.conf import settings
from django.contrib.auth.views import (LoginView, PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from apps.users.forms import (UserLoginForm, UserProfileForm,
                              UserRegistrationForm)
from apps.users.models import EmailVerification, User
from apps.users.tasks import send_email_verification


class UserProfileView(UpdateView):
    extra_context = {'title': 'Профиль'}
    model = User
    template_name = 'users/profile.html'
    form_class = UserProfileForm

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        if 'remove_avatar' in request.POST:
            user.image.delete()
        if 'resend_email' in request.POST and not user.is_verified_email:
            EmailVerification.objects.filter(user=user).delete()
            send_email_verification.delay(user.id)
        return super().post(request, *args, **kwargs)


class UserRegistrationView(SuccessMessageMixin, CreateView):
    extra_context = {'title': 'Регистрация'}
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'
    success_message = 'Вы успешно зарегистрировались! На вашу эл. почту отправлено письмо с подтверждением.'


class UserLoginView(LoginView):
    extra_context = {'title': 'Авторизация'}
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')
        return super().get(request, *args, **kwargs)


class EmailVerificationView(TemplateView):
    extra_context = {'title': 'Подтверждение эл. почты'}
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super().get(self, request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse_lazy('index'))


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'users/password_reset_email.html'
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:password_reset_done')
    extra_email_context = {'domain': settings.DOMAIN_NAME, 'site_name': 'Grace of the Gods'}

    def form_valid(self, form):
        email = form.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            return super().form_valid(form)
        else:
            form.add_error('email', 'Пользователь с таким адресом электронной почты не найден.')
            return self.form_invalid(form)


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = "users/password_reset_done.html"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "users/password_reset_complete.html"

templates/users/email_verification.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/users/email_verification.css' %}">
    <title>{{ title }}</title>
</head>
<body>
    <div class="verification-container">
        <h1>Поздравляем!</h1>
        <p>Ваша учетная запись успешно подтверждена!</p>
        <button class="continue-button" onclick="continueShopping()">Продолжить покупки</button>
    </div>

    <script>
        function continueShopping() {
            window.location.href = "{% url 'index' %}";
        }
    </script>
</body>
</html>

templates/users/login.html
{% load socialaccount %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/users/login.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>{{ title }}</title>
</head>
<body>
<div class="container">

    {% if messages or form.non_field_errors %}
        <div class="notification notification-{% if messages %}success{% else %}error{% endif %}">
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                {{ form.non_field_errors }}
            </ul>
        </div>
    {% endif %}

    <form class="login-form" action="{% url 'users:login' %}" method="post" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <label for="username">Логин:</label>
            <input type="text" id="username" name="username" required aria-required="true">
            {% if form.username.errors %}
                <span class="error">{{ form.username.errors }}</span>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="password">Пароль:</label>
            <input type="password" id="password" name="password" required aria-required="true">
            {% if form.password.errors %}
                <span class="error">{{ form.password.errors }}</span>
            {% endif %}
        </div>

        <button type="submit">Авторизация</button>

        <div class="forgot-password">
            <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        </div>

        <div class="social-login">
            <a href="#" class="social-btn google">
                <i class="fab fa-google"></i>
            </a>
            <a href="#" class="social-btn vk">
                <i class="fab fa-vk"></i>
            </a>
            <a href="{% provider_login_url 'github' %}" class="social-btn github">
                <i class="fab fa-github"></i>
            </a>
        </div>

        <div class="register">
            <span>Нужен аккаунт? </span><a href="{% url 'users:registration' %}">Зарегистрируйся!</a>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const closeBtn = document.querySelector('.close-btn');
        const notification = document.querySelector('.notification');

        if (closeBtn && notification) {
            closeBtn.addEventListener('click', () => {
                notification.style.display = 'none';
            });
        }
    });
</script>
</body>
</html>

templates/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сброс пароля</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/users/password_reset_complete.css' %}">
</head>
<body>
<div class="profile-container">
    <p>Ваш пароль был установлен. Вы можете войти сейчас.</p>
    <p><a href="{{ login_url }}" class="save-button">Войти</a></p>
</div>

</body>
</html>

templates/users/password_reset_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сброс пароля</title>
    <link rel="stylesheet" href="{% static 'css/users/password_reset_confirm.css' %}">
</head>
<body>

<div class="profile-container">
    {% if validlink %}

        <p>Пожалуйста, введите ваш новый пароль дважды, чтобы мы могли проверить, что вы ввели его правильно.</p>

        <form method="post">{% csrf_token %}

            <input type="hidden" autocomplete="username" value="{{ form.user.get_username }}">

            <div class="info-item">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">Новый пароль:</label>
                {{ form.new_password1 }}
            </div>

            <div class="info-item">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">Подтвердите пароль:</label>
                {{ form.new_password2 }}
            </div>

            <input type="submit" class="save-button" value="Изменить мой пароль">
        </form>

    {% else %}

        <p>Ссылка для сброса пароля была недействительна, возможно, потому что она уже была использована. Пожалуйста,
            запросите новый сброс пароля.</p>

    {% endif %}
</div>

</body>
</html>

templates/users/password_reset_done.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Восстановление пароля</title>
    <link rel="stylesheet" href="{% static 'css/users/password_reset_done.css' %}">
</head>
<body>
    <div class="profile-container">
        <p>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.</p>

        <p>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес, с которым вы зарегистрировались, и проверьте папку со спамом.</p>
    </div>
</body>
</html>

templates/users/password_reset_email.html
{% autoescape off %}
Вы получили это письмо, потому что запросили сброс пароля для своей учетной записи пользователя на сайте Grace of the Gods.

Пожалуйста, перейдите на эту страницу и введите новый пароль:
{% block reset_link %}
{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Ваше имя пользователя (на случай, если вы его забыли): {{ user.get_username }}

Спасибо, что используете наш сайт!
{% endautoescape %}

templates/users/password_reset_form.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Восстановление пароля</title>
    <link rel="stylesheet" href="{% static 'css/users/password_reset_form.css' %}">
</head>
<body>
    <div class="password-recovery-container">
        <p class="instruction">Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.</p>

        <form method="post" class="recovery-form">{% csrf_token %}
            <div class="form-group">
                {{ form.email.errors }}
                <div class="email-field">
                    <label for="id_email">Адрес электронной почты:</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="submit-group">
                <input type="submit" value="Восстановить пароль" class="submit-button">
            </div>
        </form>
    </div>
</body>
</html>

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/users/profile.css' %}">
{% endblock %}

{% block content %}
    <body>
        <form action="{% url 'users:profile' user.pk %}" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile-container">
                <div class="avatar-section">
                    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'img/default_avatar.jpg' %}{% endif %}"
                         alt="Avatar" class="avatar" id="avatar-image">
                    <input type="file" name="image" id="image" class="upload-avatar" accept="image/*">
                    <button type="submit" name="remove_avatar" value="true" class="remove-avatar">Удалить аватарку</button>
                </div>

                <div class="user-info">
                    <div class="info-item">
                        <label for="first_name">Имя:</label>
                        <input type="text" id="first_name" name="first_name" value="{{ form.first_name.value|default:'' }}"
                               class="editable" aria-describedby="firstNameHelp" />
                    </div>

                    <div class="info-item">
                        <label for="username">Имя пользователя:</label>
                        <input type="text" id="username" value="{{ user.username }}" class="read-only" disabled aria-disabled="true"/>
                    </div>

                    <div class="info-item">
                        <label for="email">Почта:</label>
                        <input type="email" id="email" value="{{ user.email }}" class="read-only" disabled aria-disabled="true"/>
                    </div>

                    <button class="save-button" type="submit">Сохранить изменения</button>

                    {% if not user.is_verified_email %}
                        <div class="resend-section" style="display: inline;">
                            <button type="submit" name="resend_email" value="true" class="remove-avatar">Отправить письмо для подтверждения эл. почты</button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </form>

        <div class="cart-section">
            {% if baskets %}
                <h2>Корзина</h2>
                {% for basket in baskets %}
                    <div class="cart-item">
                        <span>Товар: {{ basket.product }} Количество: {{ basket.quantity }}</span>
                        <span class="item-price">{{ basket.product.price }}</span>
                        <a href="{% url 'products:basket_remove' basket.id %}" class="remove-button">Удалить</a>
                    </div>
                {% endfor %}
                <a href="{% url 'orders:order_create' %}" class="checkout-button">Оформить заказ Товаров: {{ baskets.total_quantity }} Цена: {{ baskets.total_sum }}</a>
            {% else %}
                <h2>Корзина пуста</h2>
            {% endif %}
        </div>
    </body>
{% endblock %}

templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/users/register.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> <!-- Подключение иконок -->
    <title>{{ title }}</title>
</head>
<body>
<div class="registration-form">
    {% if form.errors %}
        <div class="notification" id="notification">
            <span class="close-btn" onclick="closeNotification()">&times;</span>
            <ul>
                {% for field, errors in form.errors.items %}
                    <li>{{ errors|join:", " }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    
    <h2>Создать аккаунт</h2>
    
    <form action="{% url 'users:registration' %}" method="post" class="form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
            {{ form.username }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
            {{ form.password1 }}
        </div>
        
        <div class="form-group">
            <label for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
            {{ form.password2 }}
        </div>
        
        <button type="submit" class="btn">Создать аккаунт</button>
    </form>
    
    <p>Уже есть аккаунт? <a href="{% url 'users:login' %}">Авторизоваться</a></p>
</div>

<script>
    function closeNotification() {
        document.getElementById("notification").style.display = "none";
    }
</script>
</body>
</html>